<?
$compare_query = "SELECT * FROM `original_text` WHERE o_text in (
'Click title to edit.', 
'Saved', 
'Preview', 
'Undo', 
'Redo', 
'Email Alerts', 
'Thank You Page', 
'Share Form', 
'Preferences', 
'Conditional Logic', 
'Form Style', 
'Setup &amp; Share', 
'Question Properties', 
'Form Tools', 
'Heading', 
'Text Box', 
'Text Area', 
'Drop Down', 
'Radio Button', 
'Check Box', 
'File Upload', 
'Submit Button', 
'Quick Tools', 
'Full Name', 
'E-mail', 
'Address', 
'Number', 
'Phone', 
'Birth Date Picker', 
'Survey Tools', 
'Star Rating', 
'Scale Rating', 
'Grading', 
'Slider', 
'Range', 
'Spinner', 
'Matrix', 
'Form Collapse', 
'Page Break', 
'Power Tools', 
'Free Text', 
'DateTime', 
'Password Box', 
'Hidden Box', 
'Captcha', 
'Image', 
'Auto Complete', 
'Payment Tools', 
'Themes', 
'Loading.. Please wait.', 
'Go Normal Screen', 
'Go Full Screen', 
'Top', 
'Go to Top', 
'OK', 
'Cancel', 
'There is an error on the wizard. Please contact Jotform Support.', 
'Copy to clipboard', 
'Copy', 
'Thank you for filling out our form.', 
'New Submission', 
'Email sent successfully.', 
'Condition Wizard', 
'show this field', 
'Remove Conditions', 
'Back', 
'Next', 
'Complete', 
'Auto Responder %s', 
'Notification %s', 
'Email Wizard', 
'Your E-Mail', 
'Your Name', 
'Provide Sender and Recipient Details', 
'Use HTML E-Mail', 
'Use Text E-Mail', 
'Enter your e-mail address to receive notifications.', 
'E-mail address should be valid.', 
'Enter your name to be used in auto responds.', 
'Enter your e-mail address to be used in auto responds.', 
'Enter a name for this e-mail.', 
'Please enter an E-mail address to quickly test your template', 
'Please Enter your email', 
'E-mail sent', 
'Are you sure you want to delete this email', 
'Confirm', 
'Delete E-Mail', 
'Close', 
'Are you sure you want to switch to plain text format? All your formatting will be lost.', 
'Are you sure you want to navigate away, you have unsaved changes.', 
'Show Advanced', 
'Hide Advanced', 
'Save', 
'Email Edited Successfully', 
'Email Edited', 
'Send Test', 
'Edit Link', 
'IP', 
'Date Time', 
'Form Title', 
'Untitled Form', 
'You have unsaved changes: Are you sure you want to discard them?', 
'Click to edit', 
'Click to change', 
'Wizard', 
'Properties', 
'Delete', 
'Required', 
'Move Up', 
'Move Down', 
'Expand', 
'Shrink', 
'Merge to above line', 
'Move to a new line', 
'Duplicate', 
'Payment Wizard', 
'Would you like to <u><b>keep the products</b></u> to be used with another payment gateway?', 
'You cannot add more than one <u>payment</u> tool. Please delete the existing one first.', 
'You cannot add more than one <u>capctha</u> tool. Please delete the existing one first.', 
'Email List', 
'Add New Email', 
'ON', 
'Close<br>Themes', 
'Add New Option', 
'Option', 
'Please enter a valid address', 
'New submission', 
'Example', 
'Oops!! A problem occurred please reload the page or clean your cookies.', 
'In order to use JotForm, you must enable <b>cookies</b> otherwise your work cannot be saved and you will lose all your changes.', 
'For more information.', 
'Form Actions', 
'Show Transparency', 
'Hide Transparency', 
'Setup E-mails', 
'Send notification and confirmation emails on submissions', 
'Redirect user to a page after submission', 
'Add form to your website or send to others', 
'Update Form Settings', 
'Setup Conditional Fields', 
'Equals To', 
'Not Equals To', 
'Contains', 
'Does not Contain', 
'Starts With', 
'Ends With', 
'Is Empty', 
'Is Filled', 
'Less Than', 
'Greater Than', 
'Before', 
'After', 
'Please select', 
'Page %d', 
'Thank you for your submission', 
' field', 
'Skip to', 
'Redirect to', 
'Display message', 
'Add New Rule', 
'Add New Condition', 
'New Form Wizard', 
'Continue', 
'Donation', 
'Account Information', 
'Payment Options', 
'Products', 
'Subscriptions', 
'Thank you', 
'Quantity', 
'Color', 
'T-Shirt Size', 
'Print Size', 
'Screen Resolution', 
'Shoe Size', 
'Please enter a donation text.', 
'You should at least add one product.', 
'You should at least add one subscription.', 
'Add New Subscription', 
'Subscription Details', 
'Save Subscription', 
'Add New Product', 
'Product Details', 
'Save Product', 
'None', 
'Enabled', 
'Finish', 
'New Subscription', 
'New Product', 
'Delete Product', 
'Edit Option', 
'Please enter an option name.', 
'Please enter various properties for this option.', 
'Click to edit this text...', 
'Pick a Date', 
'Type the above text', 
'Submit Form', 
'Total', 
'This integration has not yet been configured', 
'Run the wizard for configurations.', 
'Since there is only one product, this item will not be seen on the form.', 
'Run wizard to update payment details.', 
'Male', 
'Female', 
'N/A', 
'Monday', 
'Tuesday', 
'Wednesday', 
'Thursday', 
'Friday', 
'Saturday', 
'Sunday', 
'January', 
'February', 
'March', 
'April', 
'May', 
'June', 
'July', 
'August', 
'September', 
'October', 
'November', 
'December', 
'Daily', 
'Weekly', 
'Bi-Weekly', 
'Monthly', 
'Bi-Monthly', 
'Quarterly', 
'Semi-Yearly', 
'Yearly', 
'Bi-Yearly', 
'One Day', 
'Three Days', 
'Five Days', 
'10 Days', 
'15 Days', 
'30 Days', 
'60 Days', 
'6 Months', 
'1 Year', 
'Default', 
'Jot Theme', 
'Baby Blue', 
'Paper Grey', 
'Post-It Yellow', 
'Denim Jeans', 
'Industrial Dark', 
'Old Paper', 
'Solid Form', 
'XXL Form', 
'Title', 
'Font Family', 
'Font Size', 
'Font Color', 
'Background', 
'Form Width', 
'Label Width', 
'Label Alignment', 
'Left', 
'Right', 
'Thank You URL', 
'Thank You Text', 
'Active Redirect', 
'Send Post Data', 
'No', 
'Yes', 
'Send Email', 
'Require SSL?', 
'Unique Submission', 
'No Check', 
'Loose Check', 
'Strict Check', 
'Text', 
'Sub Heading', 
'Click to edit sub heading...', 
'Heading Type', 
'Large', 
'Small', 
'Label Align', 
'Auto', 
'Size', 
'Validation', 
'Email', 
'AlphaNumeric', 
'Alphabetic', 
'Numeric', 
'Max Size', 
'Default Value', 
'Hint Example', 
'Hover Text', 
'Columns', 
'Rows', 
'Options', 
'Option 1|Option 2|Option 3', 
'mmddyyyy', 
'ddmmyyyy', 
'24 Hour', 
'AM/PM', 
'Center', 
'Image Source', 
'Image Link', 
'Height', 
'Width', 
'Align', 
's shown', 
'Items', 
'Item 1|Item 2|Item 3', 
'Star Amount', 
'Star Style', 
'Stars', 
'Stars 2', 
'Hearts', 
'Light Bulps', 
'Lightnings', 
'Flags', 
'Shields', 
'Pluses', 
'Service Quality', 
'Overall Hygiene', 
'Responsiveness', 
'Kindness and Helpfulness', 
'Very Satisfied', 
'Satisfied', 
'Somewhat Satisfied', 
'Not Satisfied', 
'Closed', 
'Open', 
'Visible', 
'Hidden', 
'USD', 
'GBP', 
'EUR', 
'Product', 
'Subscription', 
'Font', 
'Input Type', 
'Left Aligned', 
'Right Aligned', 
'Top Aligned', 
'Special', 
'Negatives', 
'Max Value', 
'Min Value', 
'Stepping', 
'Selected', 
'Show Total', 
'Spread Columns', 
'Allow Other', 
'Currency', 
'Print Button', 
'Reset Button', 
'Heading Size', 
'Button Align', 
'Redirect Wizard', 
'Advanced Options', 
'Welcome', 
'Account Settings', 
'Logout', 
'My Forms', 
'Contact Us', 
'Terms of Use', 
'Privacy Policy', 
'Licensing Solutions', 
'Support Forums', 
'Tutorials', 
'FAQ', 
'Copyright', 
'How It Works:', 
'Drag &amp; drop fields to form', 
'Save your form', 
'Copy HTML to your web site', 
'Get responses by email ', 
'No crippleware. No ads.', 
'Why JotForm?', 
'First and Always Ahead.', 
'Free.', 
'Fast.', 
'Reliable.', 
'Language:', 
'Login to JotForm', 
'Username', 
'Password', 
'Remember Me', 
'Forgot Password?', 
'Remember your Username or E-mail?', 
'New Here?', 
'Guest', 
'Sign In to Your Account', 
'Old Password', 
'New Password', 
'New Password Again', 
'New Form', 
'New Folder', 
'All Submissions', 
'Trash Can', 
'Submissions', 
'Reports', 
'Payment Log', 
'Edit Form', 
'Clone Form', 
'Undelete Form', 
'Delete Form', 
'Account Status', 
' Restore Form ', 
' Delete Form ', 
' Empty Trash ', 
'Forum', 
'FAQs', 
'Blog', 
'Upgrade', 
'Admin', 
'Save Report', 
'Print Report', 
'Edit Report', 
'Delete Report', 
'Sign Up to JotForm!', 
'Signing up is quick and easy and in about 10 seconds you ll be on your way to publishing your forms.', 
'Print', 
'Reply', 
'Forward', 
'Edit', 
'Cancel Edit', 
'Create a new field', 
'Header', 
'Button', 
'City / State / Country', 
'PayPal', 
'PayPal Pro', 
'Authorize.Net', 
'Google Checkout', 
'2 Checkout', 
'ClickBank', 
'WorldPay', 
'OneBip', 
'Or select an existing one:', 
'Description', 
'From Address', 
'To Address', 
'Email Subject', 
'Use Default Email', 
'Settings', 
'Name', 
'Rich Formatting', 
'Enable Email?', 
'Add new Email<span>', 
'Form Fields', 
'Show Advanced Settings', 
'Show / Hide a form field', 
'Skip to a page or end of the form', 
'Send an e-mail after submission', 
'Change thank you URL after submission', 
'Change thank you message after submission', 
'Create a blank form', 
'See ready-made forms', 
'Please select a form type to create your new form.', 
' Import a form', 
' From a website ', 
'Website URL:', 
'Upload form source', 
'Select a file to upload', 
' Clone an existing form', 
'Select and existing form to clone', 
'I would like to:', 
'Sell Products', 
'Users can choose only one product', 
'Users can select multiple products', 
'Show total on the form', 
'Sell Subscriptions', 
'Users can choose only one subscription', 
'Users can select multiple subscriptions', 
'Collect Donations', 
'Donation Text', 
'Suggested Donation', 
'Add a new Item', 
'Item Details', 
'Price', 
'Additional Options', 
'Trial Period', 
'Integration Complete!', 
'Payment integration is now completed. Click Finish to save your changes.', 
'Integration <u>Almost', 
'Add Quantity Property', 
'Add a Predefined Property', 
'Add a Custom Property', 
'Option Properties', 
'Edit a product/subscription option.', 
'Redirect Options', 
'After form submission, the user should be taken to', 
'the default Thank You page.', 
'a custom URL.', 
'a customized page on the JotForm domain.', 
'Custom URL Setup', 
'Redirect the user to a web page after form submission.', 
'URL', 
'Choose if you also want to receive form data as a POST request at the above URL.', 
'Send POST Data', 
'Custom Page Setup', 
'Create your custom page by editing in the below editor.', 
'Default Thank You Page', 
'Click Finish to use this option.')";


?>
