<?
	$dbh = mysql_connect("localhost", "root", "")
		or show_error('Could not connect: ' . mysql_error());
        mysql_select_db("jotform_lang") or show_error('Could not select database');

	include "compare_query.php";
	$result = mysql_query($compare_query);
        while($row = @mysql_fetch_array($result, MYSQL_ASSOC)){
		$sameword{$row{'o_t_id'}} = $row{'o_text'};
		$oids[] = $row{'o_t_id'};
		#print_r($row);
	}

	$lang = [
			"1"	=>	"tr-TR",
			"3"	=>	"es-ES",	
			"20"	=>	"it-IT",
			"19"	=>	"fr-FR",
			"11"	=>	"de-DE",
			"7"	=>	"pt-PT",
			"43"	=>	"nl-NL",
			"96"	=>	"ca-ES",
			"80"	=>	"sv-SE",
			"66"	=>	"hu-HU",
			"117"	=>	"no-NO",
			"106"	=>	"da-DA",
			"42"	=>	"ro-RO"
    ];

	foreach($lang as $l => $ln){
		$old_override[$ln] = [];
	}
	$query = "SELECT o_t_id, l_id, suggested_translation FROM suggestions 
			WHERE o_t_id in (".join(",", $oids).") and approved=1";
	$result = mysql_query($query);
	while($row = @mysql_fetch_array($result, MYSQL_ASSOC)){
		if($lang[$row{'l_id'}]){
			#print $lang[$row{'l_id'}]."\n";
			array_push($old_override[$lang[$row{'l_id'}]], [$sameword{$row{'o_t_id'}} => $row{'suggested_translation'}]);
			#print_r($row);
		}
	}
	#print_r($old_override);

	$or = "<?\n#autogenerated\n\n\$lang_override = array(\n";
	foreach($old_override as $l =>	$a){
		$or .= "\t'$l' =>      array(\n";
		foreach($a as	$a2 => $wt){
			foreach($wt as	$w => $t){
				$or .= "\t\t'$w'          =>      '".str_replace("'", "", $t)."',\n";
			}
		}
		$or .= "\t),\n";
	}
	$or .= ")\n?>";
	file_put_contents("overlap.php", $or);


?>
